version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432 # 映射端口
    network_mode: bridge
    environment:
      - PGUSER=username #用户名
      - POSTGRES_PASSWORD=password # 密码
      - POSTGRES_DB=dify #默认数据库名称
      - TZ=Asia/Shanghai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /share/Container/postgresql/data:/var/lib/postgresql/data #挂载数据文件
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
