version: '3.9'
services:
  weaviate:
    image: semitechnologies/weaviate:1.19.0
    container_name: weaviate
    restart: unless-stopped
    network_mode: bridge
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'WVF5YThaflkYghGUSmCRgTa3tD3ngdN8pkih' # 访问密钥，请记得修改
      AUTHENTICATION_APIKEY_USERS: 'youmail@gmail.com' # 可不填
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'youmail@gmail.com'  # 可不填
    ports:
     - 8080:8080 # 映射端口
    volumes:
      - /share/Container/weaviate/data:/var/lib/weaviate #挂载数据文件
